### PR TITLE
Fix for PChem for negative value extrapolation

### PR DESCRIPTION
**Pull request by mathomp4**
This PR is needed to fix the SCM's issues with negative values hitting RRTMG (see https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/399). 

Per @mmanyin (and I'll let him say more):

> I traced the problem to MAPL_INTERP, which extrapolates if the target is off at either end.  So I wrote a wrapper routine. 
> NOTE: my code does MORE than just avoid negatives. It avoids extrapolation (which was rampant near surface).  Small diffs, but I'm sure the effects accumulate.

But at least in my testing, this fixed the SCM issues.

### CODE REVIEW

**Review by mmanyin — APPROVED** [review]
This modification prevents extrapolation of PCHEM production and loss values, solving the problem of occasional negative values.  But this is non-zero diff, so I'm looking to @wmputman and @sdrabenh to confirm that the effects are reasonable.

**Review by sdrabenh — APPROVED** [review]
This approach is reasonable. Let's proceed with getting this into a new chem release.

**Comment by wmputman** [comment]
I haven't seen any results from these tests yet.  Can someone verify that the updated pchem results are as expected and send the images to everyone?

**Comment by sdrabenh** [comment]
> I haven't seen any results from these tests yet. Can someone verify that the updated pchem results are as expected and send the images to everyone?

This experiment ran with the fix
https://gmao.gsfc.nasa.gov/intranet/research/modeling/agcm/geos5/JM_v10.17.4_L181_C90_AMIP/
Of coarse it also used the new levels.

**Pull request merged**
