### PR TITLE
stratospheric water vapor prod/loss option in pchem

### LINKED ISSUE #111: stratospheric water vapor prod/loss option in pchem
@yvikhlya, Feng added an option to the pchem code (if H2O_ProdLoss: 1 in AGCM.rc) to allow pchem to update stratospheric water vapor using stratospheric water vapor production and loss rates (rather than zonal mean water vapor values).  The stratospheric water vapor production and loss rates were pre-calculated by Eric Fleming using the Goddard-2D model under the pre-industrial conditions.  We needed the new option for pre-industrial simulations since we don’t have stratospheric water vapor fields for the pre-industrial period.

### PR DESCRIPTION
**Pull request by yvikhlya**
Closes #111. This is zero diff with default AGCM options.

### CODE REVIEW

**Review by sstrode — DISMISSED** [review]
Looks fine to me.

**Comment by bena-nasa** [comment]
the !fli2 comment lines everywhere should do

**Comment by yvikhlya** [comment]
> the !fli2 comment lines everywhere should do

Ben, do you mean `should be deleted`? 

Feng put them in CVS tag which made my life easier with merging this tag with git. I can delete them now.

**Comment by bena-nasa** [comment]
> > the !fli2 comment lines everywhere should do
> 
> Ben, do you mean `should be deleted`?
> 
> Feng put them in CVS tag which made my life easier with merging this tag with git. I can delete them now.

Yes, please delete them, no point in littering the code with comments.

**Comment by yvikhlya** [comment]
> > > the !fli2 comment lines everywhere should do
> > 
> > 
> > Ben, do you mean `should be deleted`?
> > Feng put them in CVS tag which made my life easier with merging this tag with git. I can delete them now.
> 
> Yes, please delete them, no point in littering the code with comments.

Done. I left only one `!fli2` comment left which has a meaningful part attached to it.

**Comment by mmanyin** [comment]
This PR is certainly zero-diff, if  H2O_ProdLoss: 0  (the default).
If  H2O_ProdLoss: 1,  the model fails, reporting
   Error getting varid for variable H2OprRate         -49
   NetCDF: Variable not found
Of course this is because the standard species.data file is missing the production rate.
Does it make sense to provide a version of species.data that includes the necessary rate fields,
for general users?  If so, can it be listed as an option in  gcm_run.j ?

**Comment by yvikhlya** [comment]
> This PR is certainly zero-diff, if H2O_ProdLoss: 0 (the default).
> If H2O_ProdLoss: 1, the model fails, reporting
> Error getting varid for variable H2OprRate -49
> NetCDF: Variable not found
> Of course this is because the standard species.data file is missing the production rate.
> Does it make sense to provide a version of species.data that includes the necessary rate fields,
> for general users? If so, can it be listed as an option in gcm_run.j ?

In this case this PR should be contingent on GEOSgcm_App repository? According to @sstrode this update works with S2Sv3 tag. What is different with species.data in S2Sv3 and in current set up?

**Comment by gmao-esherman** [comment]
> > This PR is certainly zero-diff, if H2O_ProdLoss: 0 (the default).
> > If H2O_ProdLoss: 1, the model fails, reporting
> > Error getting varid for variable H2OprRate -49
> > NetCDF: Variable not found
> > Of course this is because the standard species.data file is missing the production rate.
> > Does it make sense to provide a version of species.data that includes the necessary rate fields,
> > for general users? If so, can it be listed as an option in gcm_run.j ?
> 
> In this case this PR should be contingent on GEOSgcm_App repository? According to @sstrode this update works with S2Sv3 tag. What is different with species.data in S2Sv3 and in current set up?

The species.data file used in Sarah's S2Sv3 simulation, where  H2O_ProdLoss: 1, has the variables 'H2OprRate' and 'H2OlsRate'. I bet the model is crashing because it cant find these variables in file. See header information below.

float H2OprRate(time, lev, lat) ;
		H2OprRate:short_name = "H2OProdRate" ;
		H2OprRate:long_name = "H2O_chemical_prod_rate" ;
		H2OprRate:units = "kg kg-1 s-1" ;
float H2OlsRate(time, lev, lat) ;
		H2OlsRate:short_name = "H2OLossRate" ;
		H2OlsRate:long_name = "H2O_chemical_loss_rate" ;
		H2OlsRate:units = "s-1" ;

Perhaps the species.data file that has the H2OprRate and H2OlsRate becomes the default file now?

**Comment by sstrode** [comment]
There's a species.data file that works with this code, but I suspect it should not be the default since it is set up for pre-industrial conditions.

**Comment by mmanyin** [comment]
> There's a species.data file that works with this code, but I suspect it should not be the default since it is set up for pre-industrial conditions.

I suggest that the version of species.data with H2O prod and loss be copied into GMAO shared space, and that it be listed as an option in gcm_run.j, with appropriate comments.  That means a PR for GEOSgcm_App, as @yvikhlya mentioned.

**Comment by mmanyin** [comment]
I will work with @sstrode on this.

**Review by mmanyin — APPROVED** [review]
These changes are in line with the prior code, and are quite acceptable.  Note that a new version of "species.dat" is needed to make use of the new feature; this will be addressed in a PR for GEOSgcm_App soon.

**Pull request merged**
