### PR TITLE
this is single line correction to be added on top of tag: rt1.6.1

### PR DESCRIPTION
**Pull request by rtodling**
Actually, I just realized this can be put on develop w/o a problem.

### CODE REVIEW

**Review by sdrabenh — APPROVED** [review]

**Comment by mmanyin** [comment]
This one-line fix is captured in GOCART2G already.  Is it important to include it now, or can we wait for G2G?

**Comment by sdrabenh** [comment]
> This one-line fix is captured in GOCART2G already. Is it important to include it now, or can we wait for G2G?

Hi Mike, I can wait since this is already in the GOCART2G PR under evaluation. However, if getting this in now gives @rtodling a tag he can use for fpp, I am fine with it going in now. I just wanted to approve and update this branch just in case.

**Comment by mmanyin** [comment]
@sdrabenh - Considering that this is non-zero-diff, I am cautious about taking action that would trigger a lengthy approval process.  But if you can assure me that approval would be swift, and @rtodling wants the tag (faster than G2G will be delivered), then I will certainly go ahead and merge this.

**Comment by sdrabenh** [comment]
> @sdrabenh - Considering that this is non-zero-diff, I am cautious about taking action that would trigger a lengthy approval process. But if you can assure me that approval would be swift, and @rtodling wants the tag (faster than G2G will be delivered), then I will certainly go ahead and merge this.

I agree. If @rtodling is not prepared to take this PR and that comes with v1.7.0, then let's just wait until GOCART-2G percolates through.

**Comment by mathomp4** [comment]
@mmanyin I believe this is a duplicate now, right? I see the change in v1.8.0:

https://github.com/GEOS-ESM/GEOSchem_GridComp/blob/76b4411f34d01e6b9d9d2327f8eb0edca035293a/Shared/Chem_Shared/Henrys_Law_cts.F90#L192-L193

If so, I suppose you can close it and have a nice empty PR list for the first time in a while! :)

**Comment by mmanyin** [comment]
As @mathomp4 observed, this correction is part of Chemistry release v1.8.0
so I'm closing the PR.

**Pull request closed without merging**
