### PR TITLE
Update HEMCO run phases

### PR DESCRIPTION
**Pull request by christophkeller**
Simple update to the HEMCO run call. HEMCO should be called twice in HEMCO_GridComp to mimic the run sequence used in other applications (e.g., the HEMCO interface with GEOS-Chem).

### CODE REVIEW

**Comment by christophkeller** [comment]
Apologies, I realize that my note was a bit (too) short. I labelled the change zero-diff because this update only affects emissions calculated through the 'HEMCO core' functionality but not the HEMCO extensions (such as MEGAN). The HEMCO extensions have their own run call routine which is not affected by this update (HCOX_Run: [https://github.com/GEOS-ESM/GEOSchem_GridComp/blob/develop/HEMCO_GridComp/HEMCO_GridCompMod.F90#L1056]).

As far as I'm aware, the HEMCO core emissions are not being used in GOCART or GMI, even when HEMCO is turned on. But yes, the proposed change will resolve the issue that HEMCO core is currently not properly called. In that sense, it should probably be labelled as a bug fix (I updated the flags accordingly).

**Comment by mmanyin** [comment]
Thanks for clarifying between the core emissions and the extensions.  This all makes sense now.

**Review by adarmenov — DISMISSED** [review]

**Review by tclune — APPROVED** [review]
CMake changes OK.

@christophkeller please note that we may sometime be using OpenMP at the top of column physics and would want to deactivate any openmp loops at this level.

**Review by mmanyin — APPROVED** [review]
This PR is zero diff, as advertised, including when the GMI instance is run.

**Pull request merged**
