### PR TITLE
Add CCNtuning option for 2MOMENT cld_micro

### PR DESCRIPTION
**Pull request by sdrabenh**
These changes were done on behalf of @wmputman and in preparation for tuning 2MOMENT microphysics. One day AMIP, REPLAY, and 0-inc REPLAY at C48 showed all restarts and histories to be 0-diff using the default CLDMICRO:1MOMENT.

### CODE REVIEW

**Comment by adarmenov** [comment]
@sdrabenh - #71 is similar to but not the same as #65, is @dbarahon aware of this PR?

**Comment by wmputman** [comment]
> @sdrabenh - #71 is similar to but not the same as #65, is @dbarahon aware of this PR?

Yes, @dbarahon and I prepared this pull request so it could go to the top of develop. @dbarahon can verify this update.

**Comment by mmanyin** [comment]
@mathomp4  Can you trigger a re-test of the the label requirement for #71  ?  It fails to notice te 0_diff label

**Comment by sdrabenh** [comment]
@dbarahon please let @mmanyin know if these changes look good to you. If so, @mmanyin or @gmao-esherman , I hate to ask your guys again, but could one of you issue another chem tag for gcm_GC to reference? I'm really hoping to stop flooding you guys with PRs!

**Comment by dbarahon** [comment]
I am ok with #71

**Comment by sdrabenh** [comment]
Thanks @dbarahon . I'll wait to hear from @mmanyin or @gmao-esherman

**Pull request merged**
