### PR TITLE
Fixes #30. Remove sulfur code from GMI Chemistry

### LINKED ISSUE #30: GMI cannot be compiled with Bounds Checking on
If you try and build GMI Chem with `-DCMAKE_BUILD_TYPE=Debug` and Intel, you get errors like this:
```
../src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/@GEOSchem_GridComp/GMIchem_GridComp/GMI_GridComp/GmiChemistry/sulfur/aqu_sulfchem.F90(281): 
error #5561: Subscript #2 of the array SEMISS has value 0 which is less than the lower bound of 1
         snso2(:) = semiss(:, INSO2)
--------------------^
```
The issue seems to be due to `INSO2` and other parameters being set to 0:
https://github.com/GEOS-ESM/GEOSchem_GridComp/blob/68bf4994b218025ea63bfe65d544c84ab1d797dc/GMIchem_GridComp/GMI_GridComp/GmiChemistry/stratTropMech/setkin_par.h#L140-L141

This change came in from #25.

If you look at `setkin_par.h` you will see:
https://github.com/GEOS-ESM/GEOSchem_GridComp/blob/68bf4994b218025ea63bfe65d544c84ab1d797dc/GMIchem_GridComp/GMI_GridComp/GmiChemistry/stratTropMech/setkin_par.h#L60-L66

but in talking with @mmanyin, he seemed to indicate that while setting to 1 allows bounds checking, it also gives you the wrong answer! @mmanyin, can you comment more on this?

Perhaps, @tclune can think up a nice Fortran safe way of fixing this? I could fairly easily turn off bounds checking in GMI as a workaround, but it's better to fix the code correctly.

### PR DESCRIPTION
**Pull request by mathomp4**
Per @mmanyin, the sulfur code in GMI was removed in the latest CVS code but remained in Git. This commit removes it.

### CODE REVIEW

**Comment by mathomp4** [comment]
This will require testing from @mmanyin to make sure GMI isn't broken with sulfur's removal. As he said it's not there in CVS, it should work!

**Comment by mathomp4** [comment]
Note: I've made this a `hotfix` since the error is in `master` as well. If it's accepted, we can then make PRs and pull the updates into `develop` and then `dev/MAPL-2.0`.

**Comment by mathomp4** [comment]
@mmanyin If you can, can you please merge this in? (I could, but it's really your component.)

Once that's done, there will be a series of a couple more PRs to get this into `develop` and `dev/MAPL-2.0`.

**Comment by mmanyin** [comment]
After approving the PR to Master, I kept the hotfix branch around, in case we will need to use it, to update Develop.

**Pull request merged**
