### PR TITLE
Add new files for ExtData2G

### PR DESCRIPTION
**Pull request by bena-nasa**
This brings in the new yaml files for ExtData2G so those will be available when the switch is thrown to start using them. This is zero diff as I'm not getting rid of the old files yet

### CODE REVIEW

**Comment by mmanyin** [comment]
@bena-nasa Can you point us to documentation on the new ExtData?  Sound much more flexible than the original. thx

**Comment by bena-nasa** [comment]
> @bena-nasa Can you point us to documentation on the new ExtData? Sound much more flexible than the original. thx

Here is the documentation:
https://github.com/GEOS-ESM/MAPL/wiki/ExtData-Next-Generation---User-Guide
I will be presenting about this at the next theme meeting. Until all the repos that need the new files get approved no one can use this as you can only run the new or the old in MAPL from the cap, not both. I also see I forgot to add labels and update the changelog, I'll do that.

**Comment by mathomp4** [comment]
Updated labels to make sure all CI is triggered (not sure if trivial does anything to CircleCI, but just in case).

As such, I added a couple lines in `CHANGELOG.md` so that the changelog enforcer is happy.

**Comment by mathomp4** [comment]
Re-running CI after HEMCO branch removal

**Comment by mmanyin** [comment]
Clearly this is zero-diff because the YAML files are not used yet.  Am I right to assume that ExtData2G should be zero-diff to the original ExtData, if all the YAML files are crafted correctly?  There are hundreds of lines involved in this re-factoring, and reviewing them all would be a painstaking process; it would be more efficient to demonstrate zero-diff.  Is this a viable alternative?  Will there be a release with a run-time or compile-time option for which version of ExtData to use?

**Comment by bena-nasa** [comment]
> Two comments - ChemEnv_ExtData.yaml does not get copied to install/ yet (please fix). And there are 3 versions of GMI_ExtData.yaml (mirroring the 3 versions of GMI_ExtData.rc). Please delete the new yaml files under CCMI_REF-C1 and CCMI_REF-C2, those CCMI settings are out of date anyway.
@mmanyin 
Done

**Review by mmanyin — APPROVED** [review]
OK, zero diff at this point.

**Review by mathomp4 — DISMISSED** [review]
Trust in @bena-nasa !

**Review by mathomp4 — APPROVED** [review]
Re-approve!

**Pull request merged**
