### PR TITLE
Generalizing paths for MAPL utilities.

### PR DESCRIPTION
**Pull request by tclune**
This will allow the code to work with both the current MAPL and the
upcoming subdir reorg.

### CODE REVIEW

**Comment by tclune** [comment]
Note that the cmake is still a bit fragile. Ultimately the logic fo using the acg must migrate to a MAPL macro that is exported.   This is already in place for next-gen GOCART.

**Comment by mathomp4** [comment]
@mmanyin My guess is this has to be zero-diff, but as I don't know how to run GMI, it would be good to do a quick test as the generator is used with GMI (and HEMCO, but if it works for one, will work for both).

**Comment by mathomp4** [comment]
I have tested this and the models builds and is zero-diff with a normal GOCART c48 run.

**Comment by mmanyin** [comment]
Tested GMI, using HEMCO for MEGAN emissions--  zero diff.

**Pull request merged**
