### PR TITLE
Moving GOCART legacy to be sourced from GOCART repository.

### PR DESCRIPTION
**Pull request by WilliamJamieson**
This is part of a multi-repository pull request to move GOCART source into the GOCART repository instead of coming from this repository. The removed GOCART code is identical to the GOCART_GridComp code in the `v1.0.0-beta` release of the GOCART repository.

I have tested this change by running a C12 experiment for 1 day and have found the results to be zero diff.

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
The related PR on the `GEOSgcm` repository is [#257](https://github.com/GEOS-ESM/GEOSgcm/pull/257#issue-578788800).

**Review by tclune — DISMISSED** [review]
To big to review.  Crossing fingers.

**Comment by gmao-esherman** [comment]
> To big to review. Crossing fingers.

Is there a way for me to build, and test that the changes are zero-diff?

**Comment by mathomp4** [comment]
> > To big to review. Crossing fingers.
> 
> Is there a way for me to build, and test that the changes are zero-diff?

@gmao-esherman I think:
```
mepo clone -b feature/wjamieson/GOCART_legacy_changes git@github.com:GEOS-ESM/GEOSgcm.git
```
will get you the new code base to test in full.

**Comment by gmao-esherman** [comment]
> > > To big to review. Crossing fingers.
> > 
> > 
> > Is there a way for me to build, and test that the changes are zero-diff?
> 
> @gmao-esherman I think:
> 
> ```
> mepo clone -b feature/wjamieson/GOCART_legacy_changes git@github.com:GEOS-ESM/GEOSgcm.git
> ```
> 
> will get you the new code base to test in full.

Great, thank you!

**Comment by WilliamJamieson** [comment]
> To big to review. Crossing fingers.

All the changes are just removing GOCART legacy from this repository.

**Comment by tclune** [comment]
@WilliamJamieson   I understand.    It just impossible to review in any sensible manner through GitHub.   So we have to take a (small) leap of faith that nothing bad is being done unintentionally or otherwise.

**Review by gmao-esherman — APPROVED** [review]
This feature branch built and ran just fine. It also zero-diffs with develop. We're good to merge.

**Comment by mathomp4** [comment]
> This feature branch built and ran just fine. It also zero-diffs with develop. We're good to merge.

This will need coordination with @sdrabenh and @mmanyin for sure. Need a tagged version of GEOSchem_GridComp. Then @WilliamJamieson can update the `components.yaml` in https://github.com/GEOS-ESM/GEOSgcm/pull/257 along with a non-beta tag of GOCART itself.

**Comment by mmanyin** [comment]
> This will need coordination with @sdrabenh and @mmanyin for sure. Need a tagged version of GEOSchem_GridComp. Then @WilliamJamieson can update the `components.yaml` in [GEOS-ESM/GEOSgcm#257](https://github.com/GEOS-ESM/GEOSgcm/pull/257) along with a non-beta tag of GOCART itself.

I will wait to hear from @sdrabenh before committing this to CHEM 'develop', 'main',  and tagging it.
(Thanks to @gmao-esherman for testing!!)

**Comment by mmanyin** [comment]
@mathomp4  It's a shame that Elliot's review (in which he did the work of verifying zero-diff) was dismissed. Does that mean that the work needs to be done again?

**Comment by tclune** [comment]
@mmanyin No - the work does not need to be repeated.    Matt only cleared out the approvals.  Once the remaining issues are resolved we can re-review and merge.

**Comment by tclune** [comment]
Sorry - I misread your concern.   Yes - the test for zero-diffs will need to be repeated unless the additional changes are trivial.  (Eye of the beholder.)

**Comment by mmanyin** [comment]
@tclune In light of this, I recommend that we wait for the dust to settle, and no more modifications are planned, before reviewing zero-diff again.

**Comment by mathomp4** [comment]
@mmanyin Note I'm not sure the CI will ever work very well since it needs a change on GEOSgcm itself to succeed. Once we are ready for this, we can work with @sdrabenh and get it all in at once!

**Review by sdrabenh — APPROVED** [review]

**Comment by gmao-esherman** [comment]
It looks like the automated tests have failed. Who is stewarding this PR now?

**Comment by tclune** [comment]
Ugh - I thought this had been merged a while back.    The build is currently failing in a fairly basic way.

To @gmao-esherman's basic question:   squeaky wheels.   We rely on someone that wants the change to pull in others as necessary.    @mathomp4 and I will investigate.

**Comment by mathomp4** [comment]
Yes, the CI will always fail (too complex a PR).

I know @sdrabenh is looking at this. The main issue is the coordination. We need the Chem GC to issue a release and tag here and we might need a new tag (?) on GOCART as well. Then we'd need to pull in on GEOSgcm as well right away. Not hard, just needs coordination.

**Review by mathomp4 — APPROVED** [review]
Approving

**Pull request merged**
