### PR TITLE
Feature/#328/geos v10.19.4/gocart2g

### PR DESCRIPTION
**Pull request by amdasilva**
This is a revised PR for bringing GOCART-2G into GEOSch3m-GridComp.  This is a non-zero diff enhancement that has been build on top of GEOSgcm v10.19.4 (next release tag will include it). Some main highlights:

* Removes aerosols from the legacy GOCART_GridComp
* Implements bulk aerosols with the new GOGART2G_GridComp (part of the external GOCART repo). This release also includes SOA and Brown Carbon.
* Revisions to GAAS_GridComp for compatibility with the GOCART2G.
* New ExtData directory structure for easy maintenance, configuration management
* Removes legacy emission scenatious (PIESA, CMIP, etc.) Only a single AMIP scenario is currently supported.

Some issues to be resolved in the next release:

* GOCART2G exports a single AERO state including callbacks for radiation, moist and GAAS. It does not export AERO_ACI, although AERO_DP is still exported. 
* For this reason, moist now expects an AERO state, not AERO_ACI. Such a device breaks the interface of moist with MAM and CARMA. This will be fixed pending an ESMF patch to allow state aliases. See issue #154.
* GOCART2G hardwires 4 wavelengths, see GOCART issue #84

### CODE REVIEW

**Comment by mmanyin** [comment]
@amdasilva How do users generate "restart files" compatible with this PR?

**Review by tclune — DISMISSED** [review]
CMake changes ok.

**Review by adarmenov — DISMISSED** [review]

**Review by christophkeller — DISMISSED** [review]
Looks good from my perspective (in other words: I don't see anything here that would break GEOS-Chem).

**Review by mmanyin — APPROVED** [review]
These changes do not stand in isolation; they rely on modifications in other repo's: GEOSgcm, GEOSgcm_App, GEOSgcm_GridComp, GOCART. @sdrabenh and others have tested the combined changes and deem the results satisfactory, so I'm proceeding with the PR.

**Review by mathomp4 — APPROVED** [review]

**Pull request merged**
