### PR TITLE
Add hooks for Cloud-J repository for use with GEOS-Chem

### PR DESCRIPTION
**Pull request by lizziel**
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Describe the update

This PR brings in the infrastructure for including and building [Cloud-J](https://github.com/GEOS-ESM/cloud-j) which is needed for GEOS-Chem 14.3.

**NOTE:** This PR requires that Cloud-J is added to mepo to clone `GEOS-ESM/Cloud-J` branch `geos/develop` as new directory `Cloud-J/@Cloud-J`.

### Expected changes

See the [GEOS-Chem 14.3.0 version page](https://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_14.3.0).

### Required companion PRs

- https://github.com/GEOS-ESM/geos-chem/pull/4
- https://github.com/GEOS-ESM/HEMCO/pull/12

Tagging @christophkeller

### CODE REVIEW

**Comment by christophkeller** [comment]
Please merge into branch [geos/latest_gcc](https://github.com/GEOS-ESM/GEOSchem_GridComp/tree/geos/latest_gcc)

**Review by tclune — COMMENTED** [review]
CMake changes ok.

**Comment by christophkeller** [comment]
Looks fine. I can update the relevant components.yaml once this is merged. Two things:
@lizziel would you mind updating the changelog?
@mmanyin It would be good to get the ok from you on the new Cloud-J repo, too.

**Comment by mmanyin** [comment]
@christophkeller Thanks for the chance to look things over. In the latest release of this repo, directories like GMI and TR don't exist, they are populated from separate repo's during the 'mepo clone' step.  Contrast that with the approach taken here, where a Cloud-J subdirectory is introduced as part of the Chem repo...  Is the difference due to the fact that we have full control over GMI and TR, while we need a thin layer between the Cloud-J distribution and GEOS, to make them play well together?  Perhaps @mathomp4 would care to comment.

**Comment by lizziel** [comment]
@mmanyin, I created a subdirectory for Cloud-J to contain the Cloud-J repo populated during mepo clone in order to keep the GEOS-specific CMakeLists.txt file out of Cloud-J. This is how we do it for GEOS-Chem and HEMCO which is why I chose to do it this way.

**Comment by lizziel** [comment]
@mathomp4, I will push updates to changelog this afternoon. I just realized this PR also includes a HEMCO-related update for compatibility with my HEMCO and GEOS-Chem PRs that go with this.

**Comment by mathomp4** [comment]
Once everything is in, I'll give it a go. CMake is pretty flexible. One question. Are these:
```cmake
set (MODEL_GEOSCHEM TRUE) # Will need to rework to use with GMI instead
set (MAPL_ESMF TRUE)
```
used internally in the Cloud-J CMake? I just don't see anything using them in this PR.

**Comment by lizziel** [comment]
@mathomp4, changelog is now all set. Yes, `MODEL_GEOSCHEM` and `MAPL_ESMF` are used within the Cloud-J repository.

**Review by mmanyin — APPROVED** [review]
The changes look reasonable, and I trust that @lizziel and @christophkeller have tested that GEOS-Chem runs properly.

**Pull request merged**
