### PR TITLE
add predictor alarm

### PR DESCRIPTION
**Pull request by sdrabenh**
Must be taken together with pull requests [GEOSgcm_App #72](https://github.com/GEOS-ESM/GEOSgcm_App/pull/72) and [GEOSgcm_GridComp #168](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/168).

### CODE REVIEW

**Comment by mmanyin** [comment]
This is a section of code  (aerosol assimilation) that falls outside my purview, so I'm hoping that the Aerosol Team can test and approve.

**Comment by sdrabenh** [comment]
@lltakacs is actually the author of these changes. I believe these were necessary to produce zero-diff results for the new/updated IAU machinery.

**Comment by lltakacs** [comment]
The addition of the PREDICTOR alarm within GAAS was necessary in order to get zero-diff when running REGULAR Replay within the new 4DIAU paradigm.  Previously, in DAS mode, there would be no GAAS update when running the PREDICTOR since the surface aod_*.sfc files would not have been created.  However, when running REPLAY, these files DO exists and therefore must not be used when we run the PREDICTOR step.  Thus, GAAS must be made aware of when the PRECTOR alarm is active.

**Comment by gmao-esherman** [comment]
I am not familiar with this gridded component or how to exercise it. Does it need to be run with data assimilation?

**Comment by mmanyin** [comment]
This PR, taken along with the other 2,  compiles and runs with zero-diff, once I got the updated REPLAY syntax to use in AGCM.rc .

**Pull request merged**
