### PR TITLE
Feature/gaas fix for amip emissions

### PR DESCRIPTION
**Pull request by vbuchard**
When the model runs in replay with GAAS turned on and AMIP emissions chosen, the model crashes after several days with a segmentation fault. AOD becoming completely off.
This PR updates the GAAS_GridComp_Extdata.yaml in AMIP/ similar to the one in OPS.

Fixes https://github.com/GEOS-ESM/GEOSchem_GridComp/issues/281

### CODE REVIEW

**Comment by vbuchard** [comment]
**Just a note:**  this file will need to be updated if the offset is no longer 450s (a match of the heartbeat_dt in cap.rc). @bena-nasa has open a ticket to have a more flexible solution in ExtData.

**Comment by mathomp4** [comment]
> **Just a note:** this file will need to be updated if the offset is no longer 450s (a match of the heartbeat_dt in cap.rc). @bena-nasa has open a ticket to have a more flexible solution in ExtData.

Ooh. Yeah. In GEOSgcm v12 this can really not be true. The heartbeat is resolution dependent from like 1800 s to 225 or so.

**Comment by mmanyin** [comment]
> > **Just a note:** this file will need to be updated if the offset is no longer 450s (a match of the heartbeat_dt in cap.rc). @bena-nasa has open a ticket to have a more flexible solution in ExtData.
> 
> Ooh. Yeah. In GEOSgcm v12 this can really not be true. The heartbeat is resolution dependent from like 1800 s to 225 or so.

When we get to that point, I would recommend we use a token like HEARTBEAT in the yaml file that gets replaced by the run script.

**Comment by mmanyin** [comment]
Do we really want  **fail_on_missing_file** to be FALSE by default?  Won't this lead to confusion if the file path is wrong, but the user assumes that all is working properly?   What would be the down-side of  fail_on_missing_file = TRUE?

**Comment by mathomp4** [comment]
> Do we really want **fail_on_missing_file** to be FALSE by default? Won't this lead to confusion if the file path is wrong, but the user assumes that all is working properly? What would be the down-side of fail_on_missing_file = TRUE?

I think @bena-nasa knows why that is there...and I think it needs to be?

**Comment by bena-nasa** [comment]
@mmanyin, @vbuchard we probably don't want `fail_on_missing_file` in AMIP mode is my best guess. However, that is 100% necessary when GAAS is run in OPS since they run the forecast as a part of the same run where the assimilation happens.

**Comment by bena-nasa** [comment]
@mmanyin with regards to the `HEARTBEAT` issue. That's also on the to do list for ExtData

**Comment by mmanyin** [comment]
@bena-nasa Thanks for the clarifications. I will go ahead and approve the PR, with the big caveat to set fail_on_missing_file to TRUE if the model is running in non-forecast mode.

**Comment by bena-nasa** [comment]
> @bena-nasa Thanks for the clarifications. I will go ahead and approve the PR, with the big caveat to set fail_on_missing_file to TRUE if the model is running in non-forecast mode.

No, that's opposite, you want `fail_on_missing_file: true`  in forecast mode

**Review by mmanyin — APPROVED** [review]
This PR is a step in the right direction. It depends on the proper assignment of REPLAY_ANA_EXPID and REPLAY_ANA_LOCATION in AGCM.rc, and some clever code in the run script, but it works.  Two caveats, as mentioned in the discussion:  PT450S will need to be changed if the timestep changes.  And the 'fail_on_missing_file' flag for each export should probably be set to TRUE for hindcast simulations, to help guard against inadvertent mistakes.

**Pull request merged**
