### PR TITLE
Feature/acollow/hemcoscaling_extdata2g

### PR DESCRIPTION
**Pull request by acollow**
The expands the diurnal and DOW scaling of anthropogenic emissions using HEMCO to work with ExtData2G. It is contingent on a corresponding PR for GOCART.

### CODE REVIEW

**Comment by mmanyin** [comment]
I’m puzzled about many of the changes in GEOS_ChemGridComp.F90.  Connectivity of TPREC is added for GOCART, CARMA, StratChem, MAM and ACHEM;  it is taken away for GMI.  And the renaming of OX to OX_TR (between GMI and TR) has been eliminated.  I don’t understand any of those edits.

**Comment by acollow** [comment]
@mmanyin, the only change I made to GEOS_ChemGridComp.F90 is the GOCART-HEMCO connectivity. The edits you listed were already in the tag I used to base this on, 10.23.2.

**Review by christophkeller — COMMENTED** [review]
The HEMCO related updates look fine to me (changes to `HEMCOgocart2g_Config.rc`, `HEMCOgocart2g_Diagn.rc`, `HEMCOgocart2g_Spec.rc`, and the two ExtData files).
But it looks like this was added to a somewhat stale version of `GEOS_ChemGridComp.F90`, reverting some recent(-ish) commits (e.g., re-adding the TPREC connectivities that were recently removed for most GridComps: [Only GMI needs TPREC import](https://github.com/GEOS-ESM/GEOSchem_GridComp/pull/242/commits/841325f8b44301027a5739d502f82f8cef134b0e).
I suggest to recreate this PR using the latest develop branch. As far as I can tell, this only requires adding the HEMCO <-> GOCART2G connectivities to `GEOS_ChemGridComp.F90` and bringing in the updated HEMCO resource files.

**Comment by acollow** [comment]
Thanks for the suggestion @christophkeller. I don't think I will get to it today but will try to grab the develop branch and work on this tomorrow morning.

**Pull request closed without merging**
