### PR TITLE
Update configuration files for GOCART and GMI to work with HEMCO v2.2

### PR DESCRIPTION
**Pull request by christophkeller**
The MEGAN configuration inputs needed by the HEMCO configuration file were changed between HEMCO v2.1 and HEMCO v2.2. In HEMCO v2.2, MEGAN is just one single extension and the configuration file needs to reflect that. I changed the configuration files for both GOCART and GMI so that they work properly with HEMCO v2.2 and higher.

This change is zero-diff for default runs (where HEMCO is not being used) but result in non-zero changes if HEMCO is enabled as it now computes MEGAN emissions properly (again). When using the old configuration files with HEMCO v2.2, MEGAN emissions are all zero (unfortunately, this is a silent bug). The updated configuration files fix this problem.

### CODE REVIEW

**Review by mmanyin — APPROVED** [review]
This appears to work properly in the GMI/HEMCO context.  I've run it, and the emissions strongly resemble the previous version.  I have not tested the GOCART/HEMCO configuration.

**Comment by mathomp4** [comment]
> This appears to work properly in the GMI/HEMCO context. I've run it, and the emissions strongly resemble the previous version. I have not tested the GOCART/HEMCO configuration.

Huh. You can run GOCART and HEMCO? Learn something everyday! So does that mean ExtData doesn't handle the emissions? (That is: Matt doesn't know what HEMCO is. 😄 )

**Comment by christophkeller** [comment]
ExtData still reads the netCDF files and HEMCO handles how these files are aggregated and turned into an emission field, which can then be used by GOCART, GMI, or GEOS-Chem.
HEMCO supports running multiple emission instances at the same time, and we hence define different (default) emission configurations for each chemistry component (the HEMCO configuration for GEOS-Chem is shipped with the GEOS-Chem repo).

I tested this change using GOCART, and can confirm that the biogenic emissions for organic carbon (diagnostics `OCEMBG`) is zero when using the old configuration file but looks reasonable again with the configuration file update.

**Comment by adarmenov** [comment]
> I tested this change using GOCART, and can confirm that the biogenic emissions for organic carbon (diagnostics `OCEMBG`) is zero when using the old configuration file but looks reasonable again with the configuration file update.

Sounds like this PR will require changes in G2g and therefore needs to be vetted thoroughly.

**Comment by gmao-esherman** [comment]
> > I tested this change using GOCART, and can confirm that the biogenic emissions for organic carbon (diagnostics `OCEMBG`) is zero when using the old configuration file but looks reasonable again with the configuration file update.
> 
> Sounds like this PR will require changes in G2g and therefore needs to be vetted thoroughly.

I'll be sure to pay attention to the GOCART2G OC emission variables when this update is merged with GOCART2G.

**Comment by christophkeller** [comment]
Please feel free to keep me in the loop / reach out to me on this. Just to be clear - this PR does not change any import/export states or any other 'plumbing-related' things. It simply updates the HEMCO configuration file so that HEMCO calculates the MEGAN exports correctly. Also, this only affects simulations that enable HEMCO.

**Comment by adarmenov** [comment]
It will be helpful if @christophkeller clarifies if there were changes to HEMCO/MEGAN that affect any of the currently available exports besides the one that were not working properly in v2.1(?).

**Comment by christophkeller** [comment]
The update impacts all HEMCO exports related to MEGAN, i.e.: `OC_TERPENE`, `OC_MTPO`, `OC_LIMO`, and `OC_SESQ`. These are all erroneously zero right now because the MEGAN setup listed in the HEMCO configuration file is not set up properly for the new version of HEMCO (v2.2). With the proposed changes, the HEMCO configuration file meets the requirements for HEMCO v2.2 and the MEGAN exports become filled again. There are no significant underlying changes to how MEGAN calculates biogenic emissions and the new fields should match the ones in previous versions (HEMCO v2.1) closely.

**Review by adarmenov — APPROVED** [review]

**Comment by mmanyin** [comment]
Adding 'zero diff' label, because HEMCO is off by default.

**Pull request merged**
