### PR TITLE
Fixes for CMake using F2Py and LaTeX

### PR DESCRIPTION
**Pull request by mathomp4**
This update fixes some issues where systems do not have
either ImageMagick or F2Py. If F2Py is not found, then F2Py
targets are not built.

This should be taken in concert with:

GEOS-ESM/ESMA_cmake#62
GEOS-ESM/GEOSchem_GridComp#68
GEOS-ESM/GMAO_Shared#84
GEOS-ESM/UMD_Etc#11

That said, if the ESMA_cmake PR/change is not taken, the model will still build, but no f2py will run (as it's missing the `F2PY_FOUND` variable).

### CODE REVIEW

**Comment by mathomp4** [comment]
Adding @sdrabenh as a reviewer mainly to keep him aware of the multi-repo-ness of this change.

**Comment by mathomp4** [comment]
Adding @GEOS-ESM/chemistry-gatekeepers as a reviewer. Like many Chemistry-involved multi-repo PRs. We'll need @GEOS-ESM/chemistry-gatekeepers to pull into a release so we can get all the others in.

**Comment by mathomp4** [comment]
I'm actually testing now to see if this is actually just a "desired" PR rather than required. If so, it become low priority!

**Comment by mmanyin** [comment]
As with previous multi-repo PRs, I'm ready to move forward as soon as the other gatekeepers are ready.  At that point, updates to CHEM quickly move into Develop and then Master, a CHEM release is made, and then it's incorporated into a GCM (GridComp) release,  and finally a GEOSgcm release, all in short order.  Otherwise inconsistencies arise.

**Comment by sdrabenh** [comment]
@mmanyin most of the other related PRs are being/have been approved. I am ready at your convenience. I plan to issue a new release tomorrow with all of these upticked repo tags

**Pull request merged**
