### PR TITLE
Feature/sdrabenh/f525land fpp updates

### PR DESCRIPTION
**Pull request by sdrabenh**
Enhancements to GF and transport consistent with ops 525land_fpp. Must be taken in conjunction with pull requests in [GEOSgcm_GridComp#190](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/190), [GEOSgcm_App#84](https://github.com/GEOS-ESM/GEOSgcm_App/pull/84), and [GMAO_Shared#70](https://github.com/GEOS-ESM/GMAO_Shared/pull/70).

### CODE REVIEW

**Comment by mmanyin** [comment]
Which CHEM modules should perform properly with GF convection?
TR?  GOCART (which species)?  StratChem?  GMI?

**Comment by adarmenov** [comment]
@mmanyin GOCART-aerosols, CO and CO2 are/should be fine. I have not looked at TR. I have not tested StratChem and  GMI.

**Comment by mmanyin** [comment]
Based on the comments from @adarmenov  I have done brief testing of pchem+GOCART (GMI and StratChem testing will be done later). And I’ve scanned the code for implementation details.
The model runs fine, and most standard output fields appear similar enough to the previous release so as not to raise concern. Some of the fields in the geosgcm_moist collection caught my attention, such as CLCN, CNVMFC, CNVMFD, QI, REVCN and RSUCN.  I suspect that these differences have been deemed appropriate by the GEOS team.
In terms of implementation, I must comment on the “disable_convection” subroutine. This approach, which arrived earlier in Jason, is a quick-and-dirty solution for changing behavior across all the GOCART aerosol species; it is not a sound programming practice. While this Pull Request does not eliminate it, the routine is at least called from within GOCART now (rather than from MOIST), and so this is a move forward.  The case which is not addressed is TR, which allows for the Shared convection routine to be used on a species-by-species basis. We will plan to revisit this issue at a future time, so as to expedite the current PR.

**Comment by sdrabenh** [comment]
Thanks @mmanyin . Would you be able to merge develop into master and issue a tag so we can reference it in our cfg files? We look forward to any TR updates in the near future.

**Pull request merged**
