### PR TITLE
Enable use of online lightning flash rates in GEOSCHEMchem

### PR DESCRIPTION
**Pull request by christophkeller**
Make GEOS-Chem use lightning flash rates (LFR) that are computed online (in MOIST) instead of reading them from an external file.
This PR is contingent on [adding export LFR_GCC to MOIST](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/187).

### CODE REVIEW

**Comment by sdrabenh** [comment]
@christophkeller would you mind resolving the conflicted lines in these two files? Thanks

**Comment by mmanyin** [comment]
@christophkeller  This PR is zero diff for PCHEM.
But when running GEOS-Chem chemistry the model crashes -
"ExtData could not satisfy import LFR_GCC"
Please include a /dev/null entry for  LRF_GCC.

**Comment by christophkeller** [comment]
This PR needs GEOSagcm to be updated first. See this [pull request](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/187) (PR #187). LFR_GCC is then provided by MOIST (with the connectivity set in Physics_GridComp).

**Comment by mmanyin** [comment]
Sorry, I missed that first comment!  (And failed to realize that the blue text was a link to another PR).

**Comment by sdrabenh** [comment]
@GEOS-ESM/chemistry-gatekeepers we are ready to pull [#187](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/187) into the agcm. If you're are okay with this PR, please approve and tag a chem release that can be referenced by the agcm.

**Comment by mmanyin** [comment]
@mathomp4 the workflow reports a failure to compile, as of 4 days ago.  But I compiled this code in February, no problem. Are there new defaults since then? Is it trying different compilers?  I'm not sure what to make of the workflow output.

**Comment by sdrabenh** [comment]
> @mathomp4 the workflow reports a failure to compile, as of 4 days ago. But I compiled this code in February, no problem. Are there new defaults since then? Is it trying different compilers? I'm not sure what to make of the workflow output.

This depends on the GEOSgcm_GridComp pull request. Workflow will fail when multiple dependent PRs across repos are pending. It will only work when they are all in together.

**Comment by mathomp4** [comment]
> > @mathomp4 the workflow reports a failure to compile, as of 4 days ago. But I compiled this code in February, no problem. Are there new defaults since then? Is it trying different compilers? I'm not sure what to make of the workflow output.
> 
> This depends on the GEOSgcm_GridComp pull request. Workflow will fail when multiple dependent PRs across repos are pending. It will only work when they are all in together.

Yeah. This might be because we are "in the middle" of the merges. I think it was because a few days ago @sdrabenh deleted the corresponding branch on GMAO_Shared after merging it into master in preparation for a release. Thus, since the branch didn't exist, the build used the GMAO_Shared that was in the components.yaml, which doesn't have lightning_mod. I just restored @christophkeller's old branch in GMAO_Shared and relaunched CircleCI. Hopefully in 20 minutes or so, we'll see a success. If so, I can then re-delete the GMAO_Shared branch.

**Comment by sdrabenh** [comment]
> > > @mathomp4 the workflow reports a failure to compile, as of 4 days ago. But I compiled this code in February, no problem. Are there new defaults since then? Is it trying different compilers? I'm not sure what to make of the workflow output.
> > 
> > 
> > This depends on the GEOSgcm_GridComp pull request. Workflow will fail when multiple dependent PRs across repos are pending. It will only work when they are all in together.
> 
> Yeah. This might be because we are "in the middle" of the merges. I think it was because a few days ago @sdrabenh deleted the corresponding branch on GMAO_Shared after merging it into master in preparation for a release. Thus, since the branch didn't exist, the build used the GMAO_Shared that was in the components.yaml, which doesn't have lightning_mod. I just restored @christophkeller's old branch in GMAO_Shared and relaunched CircleCI. Hopefully in 20 minutes or so, we'll see a success. If so, I can then re-delete the GMAO_Shared branch.

Yes, others approved [PR#69](https://github.com/GEOS-ESM/GMAO_Shared/pull/69) merged, and deleted this branch before the whole PR was actually ready. Details were still being worked out and I don't think they were aware of the two other corresponding PRs out there.

**Comment by mathomp4** [comment]
Build succeeds with the restoration of the branch in GMAO_Shared as expected.

**Comment by sdrabenh** [comment]
Great. @mathomp4 good thinking about restoring the branch - that was the easiest solution since changes are in shared master but not referenced in a tagged released yet.

**Comment by mmanyin** [comment]
About Workflow:   Does it use mepo?  and if so, does mepo have a separate "develop" list of tags to use?  I have been testing by (1) checkout_externals -e Develop.cfg  (2) cd @GEOSchem_GridComp (3) git checkout develop  (4) git merge <feature>.    And I assume that Workflow has no way of using other PR dependencies?

**Comment by sdrabenh** [comment]
@mmanyin the workflow uses the following commands to build behind the scene:

mepo init
mepo clone
mepo develop GEOSgcm_GridComp GEOSgcm_App
mepo checkout-if-exists ${CIRCLE_BRANCH}
mepo status

where CIRCLE_BRANCH is the PR/branch name. This works well if all inter-dependent PRs use the same name because they will all be checked out. It failed for us initially because one of the 3 branches was already merged into master (changes not referenced in a tag) and the branch was deleted. Restoring the shared branch enable all 3 PRs to be checkout out once again.

**Comment by mmanyin** [comment]
> @mmanyin the workflow uses the following commands to build behind the scene:
> 
> mepo init
> mepo clone
> mepo develop GEOSgcm_GridComp GEOSgcm_App
> mepo checkout-if-exists ${CIRCLE_BRANCH}
> mepo status
> 
> where CIRCLE_BRANCH is the PR/branch name. This works well if all inter-dependent PRs use the same name because they will all be checked out. It failed for us initially because one of the 3 branches was already merged into master (changes not referenced in a tag) and the branch was deleted. Restoring the shared branch enable all 3 PRs to be checkout out once again.

This looks good, with one provision, for a CHEM PR -- the CIRCLE_BRANCH must not be missing any commits that are already in  CHEM Develop.  Perhaps a more general approach would be to mepo develop  <target repo>,   and then  git merge $CIRCLE_BRANCH  (for the target repo).

**Pull request merged**
