### PR TITLE
Feature/tclune/mepo style fixes

### PR DESCRIPTION
**Pull request by tclune**
ETA by @mathomp4: Requires ESMA_cmake v3.5.6+

### CODE REVIEW

**Review by bena-nasa — APPROVED** [review]

**Review by christophkeller — APPROVED** [review]
Not an expert in this but the changes look good to me. And certainly nice to have the symlinks removed!

**Review by mmanyin — COMMENTED** [review]
I defer to @christophkeller on this. Has the PR been tested?  Last time I tried geoschemchem_setup it did not generate a run-able experiment, so I cannot easily confirm the viability of GEOS-Chem changes.

**Comment by mathomp4** [comment]
@mmanyin I can work with @christophkeller on testing if he'd like. You'll need an update in ESMA_cmake so it'll build (only working here because @tclune did the "same branch name everywhere" trick). This will be blocked until @sdrabenh can bring in the new ESMA_cmake into GEOSgcm.

**Comment by mathomp4** [comment]
@mmanyin I think so, just remember that you'll need essentially what is in the `main` of GEOSgcm to build this (or need to update ESMA_cmake). This is due to a new function/macro @tclune created.

As far as I know, GEOSgcm `main` is okay *except* for regridding. Something bad happened with the catch regridding that needs to be fixed. So if you need to regrid, stick with a valid tag.

**Comment by mmanyin** [comment]
@mathomp4 Please clarify about regridding:  If @sdrabenh merges these into a new release (which I would assume to be a 'valid tag'), will regridding (regrid.pl) be broken?

**Comment by sdrabenh** [comment]
@mathomp4 and @mmanyin this PR and the eventual release of chem v1.7.0 will not be referenced by the gcm until a non-zero-diff uptick of the fixture. The regridding issue will hopefully be solved quickly before this release comes into play.

**Pull request merged**
