### PR TITLE
Feature/#328/geos v10.17.6/gocart2g/new extdata

### PR DESCRIPTION
**Pull request by amdasilva**
Updates achem resource files to reflect new structure of emissions in ExtData.

### CODE REVIEW

**Comment by amdasilva** [comment]
The AERO_ACI callback functionality has been folded in the main AERO state. However, due to an oversight, we have temporarily lost the ability of having different AERO providers to Radiation and MOIST (something that is useful for exploratory scientific studies but has no impact in production applications.) This feature will be reintroduced in future releases. Solution: instantiate multiple aerosol components and reintroduce AERO_ACI and AERO_Rad providers in GEOSchem_Gridcomp, having the ability of exporting different providers to MOIST and Radiation.

**Comment by adarmenov** [comment]
I can suggest two solutions that should address my concerns: 

1. In CHEM, export one more time AERO from GOCART but rename it to AERO_ACI. MAPL_StateAddExportSpecFrmChld() does not have renaming functionality, but hopefully this is still doable with some lower level MAPL.
2. In GOCART, add AERO_ACI to the export spec and copy AERO after it is fully constructed, i.e. AERO_ACI := AERO

**Review by adarmenov — APPROVED** [review]
With cc4a866 in place the PR looks good.

**Comment by amdasilva** [comment]
@mmanyin Withdrawing this PR, a new PR is forthcoming once we integrated into GEOSgcm v10.19.4. GOCART-2G restarts need bootstrapping, no good way to create restarts because of new brown carbon tracer (which was included in OC, so cannot be disentangled.) AERO_ACI issue has been dealt with given current MAPL limitation.

**Pull request closed without merging**
